name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please search [existing issues](https://github.com/raginx/gophish-ng/issues) first to avoid duplicates.

  - type: input
    id: version
    attributes:
      label: Version
      description: The version/tag you're running, or the commit hash if built from source.
      placeholder: v0.16.0
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database
      options:
        - SQLite (default)
        - MySQL
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug, and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any relevant terminal/log output - this is automatically formatted as code, no need for backticks.
      render: shell
    validations:
      required: false
