name: Docker Build Check
on:
  # Manual only for now, no need to run this on every push
  workflow_dispatch:

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
